### PR TITLE
[ELYWEB-149] Update the Ubuntu version that gets used by GitHub Actions

### PR DESCRIPTION
**Pull request by fabiobrz**
https://issues.redhat.com/browse/ELYWEB-149

### CODE REVIEW

**Comment by skyllarr** [comment]
@fabiobrz Thank you. Please make sure your commit contains issue number at the beginning just like the title of this PR.

@Ashpan There are some errors after updating of ubuntu version to ubuntu-latest, is this something you encounter? Is this because of jmockit version needing update as well?

**Comment by Ashpan** [comment]
The failure in the CI seems to be due to a missing dependency `jgroups`.
@fabiobrz could you please add the `jgroups` dependency to the parent `pom.xml` as a separate commit for the following issue. This should fix the Github actions failures.
https://issues.redhat.com/browse/ELYWEB-150

**Comment by fjuma** [comment]
@Ashpan @fabiobrz Instead of adding a new dependency on `jgroups`, could it be that we need to update the existing `infinispan` version?

**Comment by Ashpan** [comment]
Looks like updating the `infinispan` version to `9.4.23.Final` fixes the Github Actions failure too. I've updated [ELYWEB-150](https://issues.redhat.com/browse/ELYWEB-150) to upgrading `infinispan` instead.
@fabiobrz If you could make that change, that would be great

**Comment by fabiobrz** [comment]
Hi @Skyllarr, @fjuma amd @Ashpan, thanks for your feedback and sorry for caching up late.
I just looked at the logs and yep, it seems that Infinispan version bump is required.

> @fabiobrz If you could make that change, that would be great

Hi @Ashpan - Isn't there https://github.com/wildfly-security/elytron-web/pull/198 for that already?
IIUC, either ELYWEB-150 should be blocking ELYWEB-149, or ELYWEB-150 should be closed, and the commit in https://github.com/wildfly-security/elytron-web/pull/198 cherry picked in here.
Or am I missing something?

WDYT? CC @fjuma

**Comment by skyllarr** [comment]
Hi @fabiobrz ,  #198 was merged so you can go ahead and rebase your PR.

**Comment by skyllarr** [comment]
@fabiobrz Actually rebase is not needed, you are not touching the same files. I re-triggered CI checks here EDIT: Nevermind this message :D please rebase

**Comment by skyllarr** [comment]
@fabiobrz But please add issue number to the beginning of comit message.

**Comment by fabiobrz** [comment]
> @fabiobrz But please add issue number to the beginning of comit message.

:D Sure I'll do that, thanks @Skyllarr

**Comment by fabiobrz** [comment]
> > @fabiobrz But please add issue number to the beginning of comit message.
> 
> :D Sure I'll do that, thanks @Skyllarr

Done @Skyllarr - I wrongly rebased on master initially, but now should be okay.

**Review by Ashpan — APPROVED** [review]
Thanks @fabiobrz!

**Review by skyllarr — APPROVED** [review]

**Review by fjuma — APPROVED** [review]

**Comment by fjuma** [comment]
Thanks @fabiobrz!

**Pull request merged**
