### PR TITLE
[ELYWEB-152] Upgrade Undertow to 2.2.12.Final

### PR DESCRIPTION
**Pull request by nimisha-yadav**
Fixes: https://issues.redhat.com/browse/ELYWEB-152

### CODE REVIEW

**Review by fjuma — APPROVED** [review]

**Comment by fjuma** [comment]
Thanks for the PR, @nimisha-yadav!

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
@nimisha-yadav Thank you! This just needs a rebase now.

**Comment by fjuma** [comment]
@nimisha-yadav Feel free to let us know if you have any questions about how to resolve the conflict here.

**Comment by nimisha-yadav** [comment]
@fjuma @Skyllarr Sorry for the hassle. I unnecessarily complicated a simple thing and included a merge commit which is creating issues. Please review this instead #202 Thanks a lot.

**Pull request closed without merging**
