### PR TITLE
Added custom settings.xml to referrence JBoss Maven repository

### PR DESCRIPTION
**Pull request by kwart**
To resolve delayed synchronization of Elytron bits to Maven Central.

### CODE REVIEW

**Comment by darranl** [comment]
This is another one I would prefer renaming to .travis-settings.xml and then I will go ahead and merge

**Comment by kwart** [comment]
The file was renamed now.

**Comment by mchoma** [comment]
Any objection adding this repository directly into pom.xml? Solving also local runs problem.

**Comment by kwart** [comment]
@mchoma We had some discussion about it. Developers don't want to have infrastructure related info in the project. The most clean solution would be to have one central `settings.xml` for all JBoss projects and just reference it from project documentation (e.g. `README.md`). Unfortunatelly, we don't have such central place now.

**Pull request merged**
