### PR TITLE
[ELYWEB-214] Upgrade Junit to 4.11 -> 4.13.2

### PR DESCRIPTION
**Pull request by VAIBHAVCES**
[ELYWEB-214] Upgrade Junit to 4.11 -> 4.13.2

https://issues.redhat.com/browse/ELYWEB-214

image

### CODE REVIEW

**Comment by PrarthonaPaul** [comment]
Hi @VAIBHAVCES 
Thank you for the PR! 
Could you add the ELYWEB issue link in the description and update the commit message to match the JIRA issue description? Thanks

**Comment by VAIBHAVCES** [comment]
> Hi @VAIBHAVCES Thank you for the PR! Could you add the ELYWEB issue link in the description and update the commit message to match the JIRA issue description? Thanks

**Comment by VAIBHAVCES** [comment]
Sorry @PrarthonaPaul , mistakenly closed the MR. Reopned it

I updated the descripion with JIRA. Commit ID already havet the corresponding JIRA.

**Comment by fjuma** [comment]
Thanks @VAIBHAVCES! Just to let you know, I updated the base branch for the PR to 4.x (instead of 1.x).

For any other ELYWEB issues that you work on, please submit the PR against the 4.x branch. We are currently updating the ELYWEB issues to mention this so others know as well.

Feel free to let us know if you have any questions about that.

This PR looks good!

**Review by fjuma — APPROVED** [review]
Thanks very much @VAIBHAVCES!

**Review by PrarthonaPaul — APPROVED** [review]
Thanks @VAIBHAVCES 
LGTM!

**Comment by fjuma** [comment]
Hi @VAIBHAVCES, just noticed that this was closed but we hadn't merged it yet. Would you be able to re-open this?

**Comment by VAIBHAVCES** [comment]
@fjuma @PrarthonaPaul . I am very sorry actually my forked repository was not syncing 4.x branch so to sync it I deleted my old forked repo, but eventually with that it deleted this PR too. And now I am not able to reopen it.

I have reopened new PR can you please help me in get reviews on this one : https://github.com/wildfly-security/elytron-web/pull/242

Apology for inconvenience.

**Comment by fjuma** [comment]
No worries at all!

**Pull request closed without merging**
