### PR TITLE
[ELYWEB-152] Upgrade Undertow to 2.2.12.Final

### PR DESCRIPTION
**Pull request by nimisha-yadav**
Fixes: https://issues.redhat.com/browse/ELYWEB-152

### CODE REVIEW

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
@nimisha-yadav Thank you!

**Review by Ashpan — APPROVED** [review]
Thank you @nimisha-yadav!

**Comment by nimisha-yadav** [comment]
Thanks @Skyllarr @fjuma @Ashpan. The Wildfly project has helped me to complete the AnitaBorg OSD as well as the Hacktober fest. Though my contributions have been small, I learnt a lot about big-scale applications and projects. Thanks everyone for your cooperation :)

**Comment by fjuma** [comment]
That's great to hear @nimisha-yadav! Thanks very much for all your contributions! Feel free to continue contributing in the future too, we welcome contributions from the community. :)

**Pull request merged**
