### PR TITLE
[ELYWEB-237] [ELYWEB-222] Upgrade Elytron to 2.2.4.Final and add a test for single sign on across two apps with logout

### PR DESCRIPTION
**Pull request by skyllarr**
https://issues.redhat.com/browse/JBEAP-26646

https://issues.redhat.com/browse/ELYWEB-237
https://issues.redhat.com/browse/ELYWEB-222

Original PR: https://github.com/wildfly-security/elytron-web/pull/245

### CODE REVIEW

**Review by fjuma — APPROVED** [review]
Thanks @Skyllarr!

**Comment by skyllarr** [comment]
@ivassile Please review, thank you!

**Review by ivassile — APPROVED** [review]

**Comment by ivassile** [comment]
@Skyllarr We may include reference to the original PR https://github.com/wildfly-security/elytron-web/pull/245 in the comment.

**Comment by skyllarr** [comment]
Thanks @ivassile ! The https://issues.redhat.com/browse/JBEAP-26646 can be resolved. I am going to tag 4.0.1 now

**Pull request merged**
